### ISSUE TITLE
docker-compose启动报错

### ISSUE THREAD

**Issue by solon-liu** [hhyo/archer#2630] opened 2024-05-09 09:06 UTC
### 重现步骤

docker-compose -f docker-compose.yml up -d 启动报错：

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.archery.depends_on contains an invalid type, it should be an array

### 预期外的结果

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.archery.depends_on contains an invalid type, it should be an array

### 日志文本

```shell
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.archery.depends_on contains an invalid type, it should be an array
```

### 版本

1.11.1

### 部署方式

Docker

**Comment by LeoQuote** [comment] 2024-05-09 09:11
Duplicate of #2430

**Closed as not planned by LeoQuote** 2024-05-09 09:11 UTC
