### ISSUE TITLE
[ bug ] 1.8.2版本，docker-compose.yml中镜像tag号有问题，会报找不到镜像

### ISSUE THREAD

**Issue by peng19832** [hhyo/archer#1302] opened 2021-12-28 03:28 UTC

**Comment by peng19832** [comment] 2021-12-28 03:33
release的包里的配置文件有差异吧，我下载的release gz包，镜像tag号少个字母v
修改docker-compose.yml中镜像tag为：v1.8.2
![image](https://user-images.githubusercontent.com/9590209/147525201-602c9c6c-8c6e-4965-a99c-812189b31acb.png)

**Comment by LeoQuote** [comment] 2021-12-28 04:06
Duplicate of #1269

**Closed as completed by LeoQuote** 2021-12-28 04:06 UTC
